name: ShulkerShooter
version: '${project.version}'
main: com.ashkiano.shulkershooter.ShulkerShooter
api-version: '1.16'
author: AshKiano
commands:
  givesshooter:
    description: Gives a Shulker Shooter to the player.
    usage: /<command>